#prometheus.yml
global:
    #poll every 5 seconds
    scrape_interval: 5s
    external_labels:
        monitor: 'Prometheus-Monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']

    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter:9100']

    - job_name: 'application-and-jmx-exporter'
      static_configs:
        - targets: ['application-and-jmx-exporter:8081']